
// Enhanced HR-focused report fields with categories and metadata
export type HRReportField = {
	model: string;
	field: string;
	label: string;
	type: "string" | "number" | "date" | "boolean" | "enum";
	category: string;
	subcategory?: string;
	filterable: boolean;
	sortable: boolean;
	join?: string;
	dependsOn?: string[];
	description?: string;
	enumValues?: string[];
	isRequired?: boolean;
	isPII?: boolean; // Personal Identifiable Information
};

export type HRCategory = {
	id: string;
	name: string;
	description: string;
	icon: string;
	color: string;
	order: number;
};

export const hrCategories: HRCategory[] = [
	{
		id: "people",
		name: "People & Demographics",
		description: "Personal information, contact details, and demographics",
		icon: "👥",
		color: "bg-blue-50 text-blue-700 border-blue-200",
		order: 1,
	},
	{
		id: "employment",
		name: "Employment Details",
		description: "Job roles, departments, working patterns, and employment status",
		icon: "💼",
		color: "bg-green-50 text-green-700 border-green-200",
		order: 2,
	},
	{
		id: "compensation",
		name: "Compensation & Payroll",
		description: "Salary, hourly rate, tax and benefits",
		icon: "💰",
		color: "bg-yellow-50 text-yellow-700 border-yellow-200",
		order: 3,
	},
	{
		id: "time-off",
		name: "Time Off & Leave",
		description: "Leave requests, entitlements, and time off balances",
		icon: "📅",
		color: "bg-purple-50 text-purple-700 border-purple-200",
		order: 4,
	},
	{
		id: "documents",
		name: "Documents & Compliance",
		description: "Employment checks, training records, and document management",
		icon: "📋",
		color: "bg-orange-50 text-orange-700 border-orange-200",
		order: 5,
	},
	{
		id: "offboarding",
		name: "Offboarding",
		description: "Exit status, dates, tasks, and interviews",
		icon: "🚪",
		color: "bg-red-50 text-red-700 border-red-200",
		order: 6,
	},
	{
		id: "performance",
		name: "Performance & Training",
		description: "Training records, performance data, and development tracking",
		icon: "📈",
		color: "bg-indigo-50 text-indigo-700 border-indigo-200",
		order: 7,
	},
	{
		id: "forms",
		name: "Forms",
		description: "Custom forms and survey responses",
		icon: "📝",
		color: "bg-teal-50 text-teal-700 border-teal-200",
		order: 8,
	},
];

export const hrReportFields: HRReportField[] = [
	// People & Demographics
	{
		model: "User",
		field: "User.firstName",
		label: "First Name",
		type: "string",
		category: "people",
		filterable: true,
		sortable: true,
		description: "Employee's first name",
		isPII: true,
	},
	{
		model: "User",
		field: "User.lastName",
		label: "Last Name",
		type: "string",
		category: "people",
		filterable: true,
		sortable: true,
		description: "Employee's last name",
		isPII: true,
	},
	{
		model: "User",
		field: "User.email",
		label: "Email Address",
		type: "string",
		category: "people",
		filterable: true,
		sortable: true,
		description: "Primary email address",
		isPII: true,
	},
	{
		model: "User",
		field: "User.phone",
		label: "Phone Number",
		type: "string",
		category: "people",
		filterable: true,
		sortable: true,
		description: "Primary phone number",
		isPII: true,
	},
        {
                model: "User",
                field: "User.createdAt",
                label: "Date Added",
                type: "date",
                category: "people",
                filterable: true,
                sortable: true,
                description: "Date when user was added to the system",
        },
        {
                model: "User",
                field: "User.dateOfBirth",
                label: "Date of Birth",
                type: "date",
                category: "people",
                filterable: true,
                sortable: true,
                description: "Employee's date of birth",
                isPII: true,
        },
        {
                model: "User",
                field: "User.pronouns",
                label: "Pronouns",
                type: "string",
                category: "people",
                filterable: true,
                sortable: true,
                description: "Self-identified pronouns",
                isPII: true,
        },
        {
                model: "User",
                field: "User.GenderOption.label",
                label: "Gender",
                type: "string",
                category: "people",
                filterable: true,
                sortable: true,
                description: "Selected gender identity option",
                join: "User.genderOptionId = GenderOption.id",
                isPII: true,
        },
        {
                model: "User",
                field: "User.residencyStatus",
                label: "Residency Status",
                type: "string",
                category: "people",
                filterable: true,
                sortable: true,
                description: "Employee residency or visa status",
                isPII: true,
        },
        {
                model: "User",
                field: "User.addressStreet",
                label: "Street Address",
                type: "string",
                category: "people",
                filterable: true,
                sortable: true,
                description: "Primary street address",
                isPII: true,
        },
        {
                model: "User",
                field: "User.addressCity",
                label: "City",
                type: "string",
                category: "people",
                filterable: true,
                sortable: true,
                description: "City or suburb of residence",
                isPII: true,
        },
        {
                model: "User",
                field: "User.addressPostcode",
                label: "Postcode",
                type: "string",
                category: "people",
                filterable: true,
                sortable: true,
                description: "Postal or ZIP code",
                isPII: true,
        },
        {
                model: "User",
                field: "User.addressCountry",
                label: "Country",
                type: "string",
                category: "people",
                filterable: true,
                sortable: true,
                description: "Country of residence",
                isPII: true,
        },
        {
                model: "User",
                field: "_computed.primaryEmergencyContactName",
                label: "Primary Emergency Contact Name",
                type: "string",
                category: "people",
                filterable: false,
                sortable: false,
                description: "Name of the first listed emergency contact",
                dependsOn: [
                        "User.Employee.EmergencyContact.name",
                        "User.Employee.EmergencyContact.relationship",
                ],
                isPII: true,
        },
        {
                model: "User",
                field: "_computed.primaryEmergencyContactRelationship",
                label: "Primary Emergency Contact Relationship",
                type: "string",
                category: "people",
                filterable: false,
                sortable: false,
                description: "Relationship of the first listed emergency contact",
                dependsOn: [
                        "User.Employee.EmergencyContact.relationship",
                        "User.Employee.EmergencyContact.name",
                ],
                isPII: true,
        },
        {
                model: "User",
                field: "_computed.primaryEmergencyContactPhone",
                label: "Primary Emergency Contact Phone",
                type: "string",
                category: "people",
                filterable: false,
                sortable: false,
                description: "Phone number for the first listed emergency contact",
                dependsOn: [
                        "User.Employee.EmergencyContact.phone",
                        "User.Employee.EmergencyContact.name",
                ],
                isPII: true,
        },
        {
                model: "User",
                field: "_computed.primaryEmergencyContactEmail",
                label: "Primary Emergency Contact Email",
                type: "string",
                category: "people",
                filterable: false,
                sortable: false,
                description: "Email address for the first listed emergency contact",
                dependsOn: [
                        "User.Employee.EmergencyContact.email",
                        "User.Employee.EmergencyContact.name",
                ],
                isPII: true,
        },

        // Employment Details
        {
                model: "Employee",
                field: "Employee.isActive",
		label: "Employment Status",
		type: "boolean",
		category: "employment",
		filterable: true,
		sortable: true,
		description: "Whether the employee is currently active",
	},
	{
		model: "User",
		field: "User.Department_User_departmentIdToDepartment.name",
		label: "Department",
		type: "string",
		category: "employment",
		filterable: true,
		sortable: true,
		description: "Employee's department",
	},
	{
		model: "User",
		field: "User.JobRole.name",
		label: "Job Role",
		type: "string",
		category: "employment",
		filterable: true,
		sortable: true,
		description: "Employee's job role/title",
	},
	{
		model: "Employee",
		field: "Employee.startDate",
		label: "Start Date",
		type: "date",
		category: "employment",
		filterable: true,
		sortable: true,
		description: "Employee's start date",
	},
	{
		model: "WorkingPattern",
		field: "WorkingPattern.name",
		label: "Working Pattern",
		type: "string",
		category: "employment",
		filterable: true,
		sortable: true,
		join: "Employee.workingPatternId = WorkingPattern.id",
		description: "Employee's working pattern",
	},
	{
		model: "User",
		field: "User.managerId",
		label: "Manager ID",
		type: "string",
		category: "employment",
		filterable: true,
                sortable: true,
                description: "ID of the employee's manager",
        },
        {
                model: "User",
                field: "User.User.firstName",
                label: "Manager First Name",
                type: "string",
                category: "employment",
                filterable: true,
                sortable: true,
                description: "First name of the employee's manager",
                isPII: true,
        },
        {
                model: "User",
                field: "User.User.lastName",
                label: "Manager Last Name",
                type: "string",
                category: "employment",
                filterable: true,
                sortable: true,
                description: "Last name of the employee's manager",
                isPII: true,
        },
        {
                model: "User",
                field: "_computed.managerFullName",
                label: "Manager Full Name",
                type: "string",
                category: "employment",
                filterable: false,
                sortable: false,
                description: "Full name of the employee's manager",
                dependsOn: ["User.User.firstName", "User.User.lastName"],
                isPII: true,
        },
        {
                model: "Employee",
                field: "Employee.employmentType",
                label: "Employment Type",
                type: "string",
                category: "employment",
                filterable: true,
                sortable: true,
                description: "Employment type (e.g. full-time, part-time)",
        },
        {
                model: "Employee",
                field: "Employee.contractType",
                label: "Contract Type",
                type: "string",
                category: "employment",
                filterable: true,
                sortable: true,
                description: "Contract type classification",
        },
        {
                model: "Employee",
                field: "Employee.noticePeriodDays",
                label: "Notice Period (Days)",
                type: "number",
                category: "employment",
                filterable: true,
                sortable: true,
                description: "Required notice period in days",
        },
        {
                model: "Employee",
                field: "Employee.siteLocation",
                label: "Site Location",
                type: "string",
                category: "employment",
                filterable: true,
                sortable: true,
                description: "Named work site or location",
        },
        {
                model: "Employee",
                field: "Employee.locationId",
                label: "Location ID",
                type: "string",
                category: "employment",
                filterable: true,
                sortable: true,
                description: "Identifier of the linked location record",
        },

        // Compensation & Payroll
        {
                model: "Employee",
                field: "Employee.salaryAmount",
		label: "Salary Amount",
		type: "number",
		category: "compensation",
		filterable: true,
		sortable: true,
		description: "Annual salary amount",
	},
	{
		model: "Employee",
		field: "Employee.hourlyRate",
		label: "Hourly Rate",
		type: "number",
		category: "compensation",
		filterable: true,
		sortable: true,
		description: "Hourly pay rate",
	},
	{
		model: "Employee",
		field: "Employee.taxCode",
		label: "Tax Code",
		type: "string",
		category: "compensation",
		filterable: true,
		sortable: true,
		description: "Employee tax code",
	},
	{
		model: "Employee",
		field: "Employee.kiwiSaverEnrolled",
		label: "KiwiSaver Enrolled",
		type: "boolean",
		category: "compensation",
		filterable: true,
		sortable: true,
		description: "Whether employee is enrolled in KiwiSaver",
	},
	{
		model: "Employee",
		field: "Employee.kiwiSaverContribution",
		label: "KiwiSaver Contribution %",
		type: "number",
		category: "compensation",
		filterable: true,
                sortable: true,
                description: "KiwiSaver contribution percentage",
        },
        {
                model: "Employee",
                field: "Employee.irdNumber",
                label: "IRD Number",
                type: "string",
                category: "compensation",
                filterable: true,
                sortable: true,
                description: "New Zealand IRD number for payroll",
                isPII: true,
        },
        {
                model: "Employee",
                field: "Employee.bankAccountNumber",
                label: "Bank Account Number",
                type: "string",
                category: "compensation",
                filterable: true,
                sortable: true,
                description: "Primary bank account for payroll deposits",
                isPII: true,
        },

        // Time Off & Leave
        {
                model: "LeaveRequest",
                field: "LeaveRequest.startDate",
		label: "Leave Start Date",
		type: "date",
		category: "time-off",
		filterable: true,
		sortable: true,
		description: "Start date of leave request",
	},
	{
		model: "LeaveRequest",
		field: "LeaveRequest.endDate",
		label: "Leave End Date",
		type: "date",
		category: "time-off",
		filterable: true,
		sortable: true,
		description: "End date of leave request",
	},
	{
		model: "LeaveRequest",
		field: "LeaveRequest.reason",
		label: "Leave Reason",
		type: "string",
		category: "time-off",
		filterable: true,
		sortable: true,
		description: "Reason for leave request",
	},
	{
		model: "EventCategory",
		field: "EventCategory.name",
		label: "Leave Type",
		type: "string",
		category: "time-off",
		filterable: true,
		sortable: true,
		join: "LeaveRequest.eventCategoryId = EventCategory.id",
		description: "Type of leave (Annual, Sick, etc.)",
	},
	{
		model: "LeaveRequest",
		field: "LeaveRequest.EventCategory.name",
                label: "Leave Type",
                type: "string",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "Type of leave anchored under LeaveRequest for single-model reports",
        },
        {
                model: "LeaveRequest",
                field: "LeaveRequest.approvalStatus",
                label: "Leave Approval Status",
                type: "enum",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "Workflow approval status of the leave request",
        },
        {
                model: "LeaveRequest",
                field: "LeaveRequest.paidStatus",
                label: "Leave Paid Status",
                type: "enum",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "Indicates if the leave is paid or unpaid",
        },
        {
                model: "LeaveRequest",
                field: "LeaveRequest.dayType",
                label: "Leave Day Type",
                type: "enum",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "Specifies whether the leave covers a full or partial day",
        },
        {
                model: "LeaveRequest",
                field: "LeaveRequest.createdAt",
                label: "Leave Request Created",
                type: "date",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "Timestamp when the leave request was submitted",
        },
        {
                model: "LeaveRequest",
                field: "LeaveRequest.updatedAt",
                label: "Leave Request Updated",
                type: "date",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "Timestamp of the most recent leave request update",
        },
        // Leave-anchored employee fields for single-model leave reports
        {
                model: "LeaveRequest",
                field: "LeaveRequest.Employee.User.firstName",
                label: "Employee First Name",
		type: "string",
		category: "time-off",
		filterable: true,
		sortable: true,
		description: "Employee first name for the leave request",
		isPII: true,
	},
	{
		model: "LeaveRequest",
		field: "LeaveRequest.Employee.User.lastName",
		label: "Employee Last Name",
		type: "string",
		category: "time-off",
		filterable: true,
		sortable: true,
		description: "Employee last name for the leave request",
		isPII: true,
	},
	{
		model: "LeaveRequest",
		field: "LeaveRequest.Employee.Department.name",
		label: "Employee Department",
		type: "string",
		category: "time-off",
                filterable: true,
                sortable: true,
                description: "Employee department at time of leave request",
        },
        {
                model: "LeaveRequest",
                field: "LeaveRequest.User_LeaveRequest_requesterIdToUser.firstName",
                label: "Requester First Name",
                type: "string",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "First name of the person who submitted the leave request",
                isPII: true,
        },
        {
                model: "LeaveRequest",
                field: "LeaveRequest.User_LeaveRequest_requesterIdToUser.lastName",
                label: "Requester Last Name",
                type: "string",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "Last name of the person who submitted the leave request",
                isPII: true,
        },
        {
                model: "LeaveRequest",
                field: "_computed.requesterFullName",
                label: "Requester Full Name",
                type: "string",
                category: "time-off",
                filterable: false,
                sortable: false,
                description: "Full name of the leave requester",
                dependsOn: [
                        "LeaveRequest.User_LeaveRequest_requesterIdToUser.firstName",
                        "LeaveRequest.User_LeaveRequest_requesterIdToUser.lastName",
                ],
                isPII: true,
        },
        {
                model: "LeaveRequest",
                field: "LeaveRequest.User_LeaveRequest_approvedByIdToUser.firstName",
                label: "Approver First Name",
                type: "string",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "First name of the leave approver",
                isPII: true,
        },
        {
                model: "LeaveRequest",
                field: "LeaveRequest.User_LeaveRequest_approvedByIdToUser.lastName",
                label: "Approver Last Name",
                type: "string",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "Last name of the leave approver",
                isPII: true,
        },
        {
                model: "LeaveRequest",
                field: "_computed.approverFullName",
                label: "Approver Full Name",
                type: "string",
                category: "time-off",
                filterable: false,
                sortable: false,
                description: "Full name of the leave approver",
                dependsOn: [
                        "LeaveRequest.User_LeaveRequest_approvedByIdToUser.firstName",
                        "LeaveRequest.User_LeaveRequest_approvedByIdToUser.lastName",
                ],
                isPII: true,
        },
        {
                model: "LeaveRequest",
                field: "LeaveRequest.EventSubcategory.name",
                label: "Leave Reason Detail",
                type: "string",
                category: "time-off",
                filterable: true,
                sortable: true,
                description: "Specific leave subcategory such as sick reason",
        },
        {
                model: "LeaveEntitlement",
                field: "LeaveEntitlement.totalDays",
                label: "Total Leave Days",
                type: "number",
		category: "time-off",
		filterable: true,
		sortable: true,
		description: "Total leave days allocated",
	},
	{
		model: "LeaveEntitlement",
		field: "LeaveEntitlement.usedDays",
		label: "Used Leave Days",
		type: "number",
		category: "time-off",
		filterable: true,
		sortable: true,
		description: "Leave days already used",
	},
	{
		model: "LeaveRequest",
		field: "_computed.durationDays",
		label: "Used Leave Days",
		type: "number",
		category: "time-off",
		filterable: true,
		sortable: true,
		description: "Computed duration between start and end dates (inclusive)",
	},
	{
		model: "LeaveEntitlement",
		field: "LeaveEntitlement.carryoverDays",
		label: "Carryover Days",
		type: "number",
		category: "time-off",
		filterable: true,
		sortable: true,
                description: "Leave days carried over from previous period",
        },

        // Documents & Compliance
        {
                model: "EmploymentCheck",
		field: "EmploymentCheck.typeOfCheck",
		label: "Employment Check Type",
		type: "string",
		category: "documents",
		filterable: true,
                sortable: true,
                description: "Type of employment check performed",
        },
        {
                model: "EmploymentCheck",
                field: "EmploymentCheck.documentNumber",
                label: "Employment Check Document Number",
                type: "string",
                category: "documents",
                filterable: true,
                sortable: true,
                description: "Identifier recorded for the employment check document",
        },
        {
                model: "EmploymentCheck",
                field: "EmploymentCheck.dateOfIssue",
                label: "Check Issue Date",
                type: "date",
		category: "documents",
		filterable: true,
		sortable: true,
		description: "Date when employment check was issued",
	},
	{
		model: "EmploymentCheck",
		field: "EmploymentCheck.expiryDate",
		label: "Check Expiry Date",
		type: "date",
		category: "documents",
		filterable: true,
                sortable: true,
                description: "Date when employment check expires",
        },
        {
                model: "EmploymentCheck",
                field: "EmploymentCheck.documentUrl",
                label: "Employment Check Document URL",
                type: "string",
                category: "documents",
                filterable: true,
                sortable: false,
                description: "Link to the stored employment check document",
        },
        {
                model: "EmploymentCheck",
                field: "EmploymentCheck.createdAt",
                label: "Employment Check Created",
                type: "date",
                category: "documents",
                filterable: true,
                sortable: true,
                description: "When the employment check record was created",
        },
        {
                model: "EmploymentCheck",
                field: "EmploymentCheck.updatedAt",
                label: "Employment Check Updated",
                type: "date",
                category: "documents",
                filterable: true,
                sortable: true,
                description: "Last updated timestamp for the employment check",
        },
        {
                model: "DriverLicence",
                field: "DriverLicence.type",
                label: "License Type",
                type: "string",
		category: "documents",
		filterable: true,
                sortable: true,
                description: "Type of driver's license",
        },
        {
                model: "DriverLicence",
                field: "DriverLicence.licenceNumber",
                label: "License Number",
                type: "string",
                category: "documents",
                filterable: true,
                sortable: true,
                description: "Driver licence number on file",
                isPII: true,
        },
        {
                model: "DriverLicence",
                field: "DriverLicence.issueDate",
                label: "License Issue Date",
                type: "date",
                category: "documents",
                filterable: true,
                sortable: true,
                description: "Date when the licence was issued",
        },
        {
                model: "DriverLicence",
                field: "DriverLicence.expiryDate",
                label: "License Expiry Date",
                type: "date",
		category: "documents",
		filterable: true,
		sortable: true,
		description: "Date when driver's license expires",
	},

	// Offboarding
	{
		model: "Employee",
		field: "Employee.offboardingStatus",
		label: "Offboarding Status",
		type: "string",
		category: "offboarding",
		filterable: true,
		sortable: true,
		description: "High-level offboarding status on employee record",
	},
	{
		model: "Employee",
		field: "Employee.offboardingDate",
		label: "Offboarding Date",
		type: "date",
		category: "offboarding",
		filterable: true,
		sortable: true,
		description: "Planned offboarding date",
	},
	{
		model: "EmployeeOffboarding",
		field: "EmployeeOffboarding.status",
		label: "Exit Status",
		type: "string",
		category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Detailed exit workflow status",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.lastWorkingDate",
		label: "Last Working Date",
		type: "date",
		category: "offboarding",
		filterable: true,
		sortable: true,
		description: "Employee's final working day",
	},
	{
		model: "EmployeeOffboarding",
		field: "EmployeeOffboarding.offboardingReason",
		label: "Offboarding Reason",
		type: "string",
		category: "offboarding",
		filterable: true,
                sortable: true,
                description: "Reason for leaving",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.exitInterviewRequired",
                label: "Exit Interview Required",
                type: "boolean",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Whether exit interview is required",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.offboardingType",
                label: "Offboarding Type",
                type: "string",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Categorisation of the offboarding (e.g. resignation, termination)",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.isVoluntary",
                label: "Voluntary Exit",
                type: "boolean",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Indicates if the exit was voluntary",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.resignationDate",
                label: "Resignation Date",
                type: "date",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Date the resignation was submitted",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.actualLeaveDate",
                label: "Actual Leave Date",
                type: "date",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Confirmed final date of employment",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.assetsReturned",
                label: "Assets Returned",
                type: "boolean",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Whether company assets have been returned",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.assetsReturnedAt",
                label: "Assets Returned At",
                type: "date",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Timestamp when assets were recorded as returned",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.handoverCompleted",
                label: "Handover Completed",
                type: "boolean",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Indicates if the handover checklist is complete",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.handoverCompletedAt",
                label: "Handover Completed At",
                type: "date",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Timestamp the handover was completed",
        },
        {
                model: "EmployeeOffboarding",
                field: "_computed.accessRemoved",
                label: "Access Removed",
                type: "boolean",
                category: "offboarding",
                filterable: false,
                sortable: false,
                description: "Indicates if system access has been removed",
                dependsOn: ["EmployeeOffboarding.accessRemovedAt"],
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.accessRemovedAt",
                label: "Access Removed At",
                type: "date",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Timestamp when access removal was completed",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.finalPayAmount",
                label: "Final Pay Amount",
                type: "number",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Calculated final pay amount",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.unusedLeavePayment",
                label: "Unused Leave Payment",
                type: "number",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Payment made for unused leave",
        },
        {
                model: "EmployeeOffboarding",
                field: "EmployeeOffboarding.benefitsEndDate",
                label: "Benefits End Date",
                type: "date",
                category: "offboarding",
                filterable: true,
                sortable: true,
                description: "Date when benefits coverage ends",
        },

        // Performance & Training
        {
                model: "TrainingRecord",
                field: "TrainingRecord.dateCompleted",
		label: "Training Completion Date",
		type: "date",
		category: "performance",
		filterable: true,
		sortable: true,
		description: "Date when training was completed",
	},
	{
		model: "TrainingRecord",
		field: "TrainingRecord.expiryDate",
		label: "Training Expiry Date",
		type: "date",
		category: "performance",
		filterable: true,
		sortable: true,
		description: "Date when training expires",
	},
	{
		model: "Course",
		field: "Course.name",
		label: "Course Name",
		type: "string",
		category: "performance",
		filterable: true,
		sortable: true,
		join: "TrainingRecord.courseId = Course.id",
		description: "Name of the training course",
	},
	{
		model: "TrainingProvider",
		field: "TrainingProvider.name",
		label: "Training Provider",
		type: "string",
		category: "performance",
		filterable: true,
		sortable: true,
                join: "TrainingRecord.providerId = TrainingProvider.id",
                description: "Name of the training provider",
        },
        {
                model: "TrainingRecord",
                field: "TrainingRecord.documentId",
                label: "Training Document ID",
                type: "string",
                category: "performance",
                filterable: true,
                sortable: true,
                description: "Reference to supporting training documentation",
        },
];

// Helper functions
export function getFieldsByCategory(categoryId: string): HRReportField[] {
	return hrReportFields.filter(field => field.category === categoryId);
}

export function getCategoryById(categoryId: string): HRCategory | undefined {
	return hrCategories.find(cat => cat.id === categoryId);
}

export function getFieldByKey(fieldKey: string): HRReportField | undefined {
	return hrReportFields.find(field => field.field === fieldKey);
}

export function groupFieldsByCategory(): Record<string, HRReportField[]> {
	const grouped: Record<string, HRReportField[]> = {};
	
	hrCategories.forEach(category => {
		grouped[category.id] = getFieldsByCategory(category.id);
	});
	
	return grouped;
}

// Report templates for common HR use cases
export type ReportTemplate = {
	id: string;
	name: string;
	description: string;
	category: string;
	icon: string;
	defaultFields: string[];
	suggestedFilters?: Array<{
		field: string;
		operator: string;
		value?: any;
		value2?: any;
	}>;
	defaultSort?: { field: string; direction: "asc" | "desc" };
};

export const hrReportTemplates: ReportTemplate[] = [];

