import type { ReportFilter, SortConfig } from "@/lib/reportFilters";
import type { LucideIcon } from "lucide-react";
import {
  Palmtree,
  CalendarDays,
  CalendarClock,
  Settings,
  AlertTriangle,
  Thermometer,
  Sparkles,
  CreditCard,
  Globe2,
  Shield,
  Car,
  GraduationCap,
  Building2,
  BarChart3,
  DoorOpen,
  CheckCircle2,
  Hourglass,
  Clock,
  Clock3,
  ClipboardList,
  XCircle,
  DollarSign,
} from "lucide-react";

type ReportFilterTemplate = Omit<ReportFilter, "id">;

export interface ReportLibraryEntry {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string; // Legacy emoji support
  iconComponent?: LucideIcon; // Modern Lucide icon
  engine: "dynamic" | "custom" | "external";
  defaultFields: string[];
  suggestedFilters?: ReportFilterTemplate[];
  defaultSort?: SortConfig;
  reportType?: string;
  externalUrl?: string;
}

export const reportLibrary: ReportLibraryEntry[] = [
  {
    id: "annual-leave-balances",
    name: "Annual Leave Balances",
    description:
      "Current balances by employee, including carryover and remaining entitlement.",
    category: "time-off",
    icon: "🌴",
    iconComponent: Palmtree,
    engine: "custom",
    defaultFields: [
      "Employee.User.firstName",
      "Employee.User.lastName",
      "Employee.Department.name",
      "Employee.JobRole.name",
      "LeaveEntitlement.EventCategory.name",
      "LeaveEntitlement.totalDays",
      "LeaveEntitlement.usedDays",
      "LeaveEntitlement.carryoverDays",
      "_computed.remainingEntitlement",
    ],
    suggestedFilters: [
      { field: "Employee.isActive", operator: "equals", value: true },
    ],
    defaultSort: { field: "_computed.remainingEntitlement", direction: "asc" },
    reportType: "annualLeaveBalances",
  },
  {
    id: "on-leave-today",
    name: "Staff on Leave Today",
    description:
      "Approved leave requests that cover today, with employee and department context.",
    category: "time-off",
    icon: "📆",
    iconComponent: CalendarDays,
    engine: "dynamic",
    defaultFields: [
      "LeaveRequest.Employee.User.firstName",
      "LeaveRequest.Employee.User.lastName",
      "LeaveRequest.Employee.Department.name",
      "LeaveRequest.EventCategory.name",
      "LeaveRequest.startDate",
      "LeaveRequest.endDate",
      "_computed.durationDays",
      "LeaveRequest.approvalStatus",
    ],
    suggestedFilters: [
      { field: "LeaveRequest.approvalStatus", operator: "equals", value: "APPROVED" },
      {
        field: "LeaveRequest.startDate",
        operator: "date_before",
        value: new Date().toISOString(),
      },
      {
        field: "LeaveRequest.endDate",
        operator: "date_after",
        value: new Date().toISOString(),
      },
    ],
    defaultSort: { field: "LeaveRequest.startDate", direction: "asc" },
  },
  {
    id: "upcoming-leave",
    name: "Upcoming Leave (30 days)",
    description: "Future approved leave in the next 30 days for roster planning.",
    category: "time-off",
    icon: "🗓️",
    iconComponent: CalendarClock,
    engine: "dynamic",
    defaultFields: [
      "LeaveRequest.Employee.User.firstName",
      "LeaveRequest.Employee.User.lastName",
      "LeaveRequest.Employee.Department.name",
      "LeaveRequest.EventCategory.name",
      "LeaveRequest.startDate",
      "LeaveRequest.endDate",
      "_computed.durationDays",
      "LeaveRequest.approvalStatus",
    ],
    suggestedFilters: [
      { field: "LeaveRequest.approvalStatus", operator: "equals", value: "APPROVED" },
      {
        field: "LeaveRequest.startDate",
        operator: "date_in_next",
        value: { amount: 30, unit: "days" },
      },
    ],
    defaultSort: { field: "LeaveRequest.startDate", direction: "asc" },
  },
  {
    id: "pending-leave-approvals",
    name: "Pending Leave Approvals",
    description:
      "Leave requests waiting on approval, including requester and approver details.",
    category: "time-off",
    icon: "🛠️",
    iconComponent: Settings,
    engine: "dynamic",
    defaultFields: [
      "LeaveRequest.Employee.User.firstName",
      "LeaveRequest.Employee.User.lastName",
      "LeaveRequest.Employee.Department.name",
      "LeaveRequest.EventCategory.name",
      "LeaveRequest.startDate",
      "LeaveRequest.endDate",
      "LeaveRequest.approvalStatus",
      "_computed.requesterFullName",
      "_computed.approverFullName",
    ],
    suggestedFilters: [
      { field: "LeaveRequest.approvalStatus", operator: "equals", value: "PENDING" },
    ],
    defaultSort: { field: "LeaveRequest.createdAt", direction: "asc" },
  },
  {
    id: "low-leave-balances",
    name: "Low Leave Balances",
    description: "Employees with 2 days or fewer remaining leave entitlement.",
    category: "time-off",
    icon: "⚠️",
    iconComponent: AlertTriangle,
    engine: "custom",
    defaultFields: [
      "Employee.User.firstName",
      "Employee.User.lastName",
      "Employee.Department.name",
      "Employee.JobRole.name",
      "LeaveEntitlement.EventCategory.name",
      "LeaveEntitlement.totalDays",
      "LeaveEntitlement.usedDays",
      "LeaveEntitlement.carryoverDays",
      "_computed.remainingEntitlement",
    ],
    suggestedFilters: [
      { field: "Employee.isActive", operator: "equals", value: true },
    ],
    defaultSort: { field: "_computed.remainingEntitlement", direction: "asc" },
    reportType: "annualLeaveBalances",
  },
  {
    id: "sick-leave-usage",
    name: "Sick Leave Usage YTD",
    description:
      "Total sick leave days taken per employee in the current calendar year.",
    category: "time-off",
    icon: "🤒",
    iconComponent: Thermometer,
    engine: "custom",
    defaultFields: [
      "Employee.User.firstName",
      "Employee.User.lastName",
      "Employee.Department.name",
      "Employee.JobRole.name",
      "sickLeaveTaken",
    ],
    suggestedFilters: [
      { field: "Employee.isActive", operator: "equals", value: true },
    ],
    defaultSort: { field: "sickLeaveTaken", direction: "desc" },
    reportType: "sickLeaveUsageYTD",
  },
  {
    id: "new-starters",
    name: "New Starters (Next 30 days)",
    description: "Employees starting soon to support onboarding planning.",
    category: "employment",
    icon: "✨",
    iconComponent: Sparkles,
    engine: "dynamic",
    defaultFields: [
      "Employee.User.firstName",
      "Employee.User.lastName",
      "Employee.User.email",
      "Employee.Department.name",
      "Employee.JobRole.name",
      "Employee.startDate",
    ],
    suggestedFilters: [
      {
        field: "Employee.startDate",
        operator: "date_in_next",
        value: { amount: 30, unit: "days" },
      },
      { field: "Employee.isActive", operator: "equals", value: true },
    ],
    defaultSort: { field: "Employee.startDate", direction: "asc" },
  },
  {
    id: "missing-payroll-details",
    name: "Missing Payroll Details",
    description: "Employees missing IRD or bank details for payroll readiness.",
    category: "compensation",
    icon: "💳",
    iconComponent: CreditCard,
    engine: "dynamic",
    defaultFields: [
      "Employee.User.firstName",
      "Employee.User.lastName",
      "Employee.User.email",
      "Employee.Department.name",
      "Employee.JobRole.name",
      "Employee.irdNumber",
      "Employee.bankAccountNumber",
    ],
    suggestedFilters: [
      { field: "Employee.isActive", operator: "equals", value: true },
      { field: "Employee.irdNumber", operator: "is_null" },
    ],
    defaultSort: { field: "Employee.Department.name", direction: "asc" },
  },
  {
    id: "kiwisaver-summary",
    name: "KiwiSaver Summary",
    description: "Shows who is enrolled in KiwiSaver and their contribution rates.",
    category: "compensation",
    icon: "🥝",
    iconComponent: Globe2,
    engine: "dynamic",
    defaultFields: [
      "Employee.User.firstName",
      "Employee.User.lastName",
      "Employee.User.email",
      "Employee.Department.name",
      "Employee.JobRole.name",
      "Employee.kiwiSaverEnrolled",
      "Employee.kiwiSaverContribution",
    ],
    suggestedFilters: [
      { field: "Employee.isActive", operator: "equals", value: true },
    ],
    defaultSort: { field: "Employee.Department.name", direction: "asc" },
  },
  {
    id: "right-to-work-expiries",
    name: "Right to Work Expiries",
    description: "Employment check expiries in the next 90 days for visa compliance.",
    category: "documents",
    icon: "🛂",
    iconComponent: Shield,
    engine: "dynamic",
    defaultFields: [
      "EmploymentCheck.Employee.User.firstName",
      "EmploymentCheck.Employee.User.lastName",
      "EmploymentCheck.Employee.Department.name",
      "EmploymentCheck.typeOfCheck",
      "EmploymentCheck.documentNumber",
      "EmploymentCheck.expiryDate",
      "EmploymentCheck.documentUrl",
    ],
    suggestedFilters: [
      {
        field: "EmploymentCheck.expiryDate",
        operator: "date_in_next",
        value: { amount: 90, unit: "days" },
      },
    ],
    defaultSort: { field: "EmploymentCheck.expiryDate", direction: "asc" },
  },
  {
    id: "driver-licence-expiries",
    name: "Driver Licence Expiries",
    description: "Upcoming driver licence expiries for safety-critical roles.",
    category: "documents",
    icon: "🚗",
    iconComponent: Car,
    engine: "dynamic",
    defaultFields: [
      "DriverLicence.Employee.User.firstName",
      "DriverLicence.Employee.User.lastName",
      "DriverLicence.Employee.Department.name",
      "DriverLicence.type",
      "DriverLicence.licenceNumber",
      "DriverLicence.expiryDate",
    ],
    suggestedFilters: [
      {
        field: "DriverLicence.expiryDate",
        operator: "date_in_next",
        value: { amount: 90, unit: "days" },
      },
    ],
    defaultSort: { field: "DriverLicence.expiryDate", direction: "asc" },
  },
  {
    id: "training-expiries",
    name: "Training Expiries",
    description: "Training records expiring soon to keep compliance on track.",
    category: "performance",
    icon: "🎓",
    iconComponent: GraduationCap,
    engine: "dynamic",
    defaultFields: [
      "TrainingRecord.Employee.User.firstName",
      "TrainingRecord.Employee.User.lastName",
      "TrainingRecord.Employee.Department.name",
      "Course.name",
      "TrainingRecord.dateCompleted",
      "TrainingRecord.expiryDate",
      "TrainingProvider.name",
    ],
    suggestedFilters: [
      {
        field: "TrainingRecord.expiryDate",
        operator: "date_in_next",
        value: { amount: 90, unit: "days" },
      },
    ],
    defaultSort: { field: "TrainingRecord.expiryDate", direction: "asc" },
  },
  {
    id: "department-roster",
    name: "Department Roster",
    description: "Active employees with department, job role, contact, and pattern.",
    category: "employment",
    icon: "🏢",
    iconComponent: Building2,
    engine: "dynamic",
    defaultFields: [
      "Employee.User.firstName",
      "Employee.User.lastName",
      "Employee.User.email",
      "Employee.User.phone",
      "Employee.Department.name",
      "Employee.JobRole.name",
      "Employee.isActive",
      "Employee.startDate",
      "WorkingPattern.name",
    ],
    suggestedFilters: [
      { field: "Employee.isActive", operator: "equals", value: true },
    ],
    defaultSort: { field: "Employee.Department.name", direction: "asc" },
  },
  {
    id: "headcount-by-department",
    name: "Headcount by Department",
    description: "Active headcount totals by department for snapshot reporting.",
    category: "employment",
    icon: "📊",
    iconComponent: BarChart3,
    engine: "custom",
    defaultFields: [
      "departmentName",
      "headcount",
      "activeHeadcount",
    ],
    defaultSort: { field: "headcount", direction: "desc" },
    reportType: "headcountByDepartment",
  },
  {
    id: "offboarding-pipeline",
    name: "Offboarding Pipeline",
    description: "Employees in offboarding with key steps and dates.",
    category: "offboarding",
    icon: "🚪",
    iconComponent: DoorOpen,
    engine: "dynamic",
    defaultFields: [
      "EmployeeOffboarding.Employee.User.firstName",
      "EmployeeOffboarding.Employee.User.lastName",
      "EmployeeOffboarding.status",
      "EmployeeOffboarding.lastWorkingDate",
      "EmployeeOffboarding.offboardingReason",
      "EmployeeOffboarding.assetsReturned",
      "EmployeeOffboarding.handoverCompleted",
      "EmployeeOffboarding.accessRemovedAt",
    ],
    suggestedFilters: [
      { field: "EmployeeOffboarding.status", operator: "not_equals", value: "COMPLETED" },
    ],
    defaultSort: { field: "EmployeeOffboarding.lastWorkingDate", direction: "asc" },
  },
  {
    id: "approved-timesheets",
    name: "Approved Timesheets",
    description: "All approved timesheets with hours breakdown for payroll processing.",
    category: "time-tracking",
    icon: "✅",
    iconComponent: CheckCircle2,
    engine: "dynamic",
    defaultFields: [
      "Timesheet.Employee.User.firstName",
      "Timesheet.Employee.User.lastName",
      "Timesheet.Employee.Department.name",
      "Timesheet.periodStart",
      "Timesheet.periodEnd",
      "Timesheet.totalHours",
      "Timesheet.regularHours",
      "Timesheet.overtimeHours",
      "Timesheet.approvedAt",
      "_computed.approvedByFullName",
    ],
    suggestedFilters: [
      { field: "Timesheet.approvalStatus", operator: "equals", value: "APPROVED" },
    ],
    defaultSort: { field: "Timesheet.approvedAt", direction: "desc" },
  },
  {
    id: "pending-timesheet-approvals",
    name: "Pending Timesheet Approvals",
    description: "Timesheets awaiting approval with submission details.",
    category: "time-tracking",
    icon: "⏳",
    iconComponent: Hourglass,
    engine: "dynamic",
    defaultFields: [
      "Timesheet.Employee.User.firstName",
      "Timesheet.Employee.User.lastName",
      "Timesheet.Employee.Department.name",
      "Timesheet.periodStart",
      "Timesheet.periodEnd",
      "Timesheet.totalHours",
      "Timesheet.submittedAt",
      "Timesheet.approvalStatus",
    ],
    suggestedFilters: [
      { field: "Timesheet.approvalStatus", operator: "equals", value: "PENDING" },
    ],
    defaultSort: { field: "Timesheet.submittedAt", direction: "asc" },
  },
  {
    id: "overtime-hours-report",
    name: "Overtime Hours Report",
    description: "Timesheets with overtime hours for cost analysis.",
    category: "time-tracking",
    icon: "⏰",
    iconComponent: Clock,
    engine: "dynamic",
    defaultFields: [
      "Timesheet.Employee.User.firstName",
      "Timesheet.Employee.User.lastName",
      "Timesheet.Employee.Department.name",
      "Timesheet.Employee.JobRole.name",
      "Timesheet.periodStart",
      "Timesheet.periodEnd",
      "Timesheet.regularHours",
      "Timesheet.overtimeHours",
      "Timesheet.approvalStatus",
    ],
    suggestedFilters: [
      { field: "Timesheet.overtimeHours", operator: "greater_than", value: 0 },
    ],
    defaultSort: { field: "Timesheet.overtimeHours", direction: "desc" },
  },
  {
    id: "time-entries-detailed",
    name: "Detailed Time Entries",
    description: "Individual time entries with clock in/out times and notes.",
    category: "time-tracking",
    icon: "🕐",
    iconComponent: Clock3,
    engine: "dynamic",
    defaultFields: [
      "TimesheetEntry.Timesheet.Employee.User.firstName",
      "TimesheetEntry.Timesheet.Employee.User.lastName",
      "TimesheetEntry.Timesheet.Employee.Department.name",
      "TimesheetEntry.date",
      "TimesheetEntry.startTime",
      "TimesheetEntry.endTime",
      "TimesheetEntry.breakMinutes",
      "TimesheetEntry.hours",
      "TimesheetEntry.isOvertime",
      "TimesheetEntry.notes",
    ],
    suggestedFilters: [],
    defaultSort: { field: "TimesheetEntry.date", direction: "desc" },
  },
  {
    id: "timesheet-approval-audit",
    name: "Timesheet Approval Audit Trail",
    description: "Complete audit trail of timesheet approvals with approver comments.",
    category: "time-tracking",
    icon: "📋",
    iconComponent: ClipboardList,
    engine: "dynamic",
    defaultFields: [
      "TimesheetApprovalDecision.Stage.Timesheet.Employee.User.firstName",
      "TimesheetApprovalDecision.Stage.Timesheet.Employee.User.lastName",
      "TimesheetApprovalDecision.approverId",
      "TimesheetApprovalDecision.status",
      "TimesheetApprovalDecision.comments",
      "TimesheetApprovalDecision.respondedAt",
    ],
    suggestedFilters: [],
    defaultSort: { field: "TimesheetApprovalDecision.respondedAt", direction: "desc" },
  },
  {
    id: "rejected-timesheets",
    name: "Rejected Timesheets",
    description: "Timesheets that were rejected with reasons for follow-up.",
    category: "time-tracking",
    icon: "❌",
    iconComponent: XCircle,
    engine: "dynamic",
    defaultFields: [
      "Timesheet.Employee.User.firstName",
      "Timesheet.Employee.User.lastName",
      "Timesheet.Employee.Department.name",
      "Timesheet.periodStart",
      "Timesheet.periodEnd",
      "Timesheet.totalHours",
      "Timesheet.rejectedReason",
      "Timesheet.submittedAt",
    ],
    suggestedFilters: [
      { field: "Timesheet.approvalStatus", operator: "equals", value: "REJECTED" },
    ],
    defaultSort: { field: "Timesheet.submittedAt", direction: "desc" },
  },
  {
    id: "payroll-export",
    name: "Payroll Export",
    description: "Export approved timesheets for payroll processing in CSV, Excel, or JSON format with comprehensive employee and time tracking data.",
    category: "time-tracking",
    icon: "💰",
    iconComponent: DollarSign,
    engine: "external",
    defaultFields: [],
    externalUrl: "/admin/payroll",
  },
];

export function getReportLibrary() {
  return reportLibrary;
}

