// Auto-generated reportFields.ts with proper PascalCase model prefixes

export type ReportField = {
  model: string;
  field: string;
  label: string;
  type: "string" | "number" | "date" | "boolean";
  filterable: boolean;
  join?: string;
  dependsOn?: string[];
};

export const reportFields: ReportField[] = [
  {
    model: "User",
    field: "User.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "User",
    field: "User.email",
    label: "email",
    type: "string",
    filterable: true,
  },
  {
    model: "User",
    field: "User.password",
    label: "password",
    type: "string",
    filterable: true,
  },
  {
    model: "User",
    field: "User.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "User",
    field: "User.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "User",
    field: "User.emailVerified",
    label: "emailVerified",
    type: "date",
    filterable: true,
  },
  {
    model: "User",
    field: "User.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "User",
    field: "User.departmentId",
    label: "departmentId",
    type: "string",
    filterable: true,
  },
  {
    model: "User",
    field: "User.firstName",
    label: "firstName",
    type: "string",
    filterable: true,
  },
  {
    model: "User",
    field: "User.isActivated",
    label: "isActivated",
    type: "boolean",
    filterable: true,
  },
  {
    model: "User",
    field: "User.jobRoleId",
    label: "jobRoleId",
    type: "string",
    filterable: true,
  },
  {
    model: "User",
    field: "User.lastName",
    label: "lastName",
    type: "string",
    filterable: true,
  },
  {
    model: "User",
    field: "User.managerId",
    label: "managerId",
    type: "string",
    filterable: true,
  },
  {
    model: "User",
    field: "User.phone",
    label: "phone",
    type: "string",
    filterable: true,
  },
  {
    model: "User",
    field: "User.companyId",
    label: "companyId",
    type: "string",
    filterable: true,
  },
  {
    model: "ActivationToken",
    field: "ActivationToken.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "ActivationToken",
    field: "ActivationToken.token",
    label: "token",
    type: "string",
    filterable: true,
  },
  {
    model: "ActivationToken",
    field: "ActivationToken.userId",
    label: "userId",
    type: "string",
    filterable: true,
  },
  {
    model: "ActivationToken",
    field: "ActivationToken.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "Employee",
    field: "Employee.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "Employee",
    field: "Employee.userId",
    label: "userId",
    type: "string",
    filterable: true,
  },
  {
    model: "Employee",
    field: "Employee.isActive",
    label: "isActive",
    type: "boolean",
    filterable: true,
  },
  {
    model: "Employee",
    field: "Employee.workingPatternId",
    label: "workingPatternId",
    type: "string",
    filterable: true,
  },
  {
    model: "Employee",
    field: "Employee.departmentId",
    label: "departmentId",
    type: "string",
    filterable: true,
  },
  {
    model: "EmployeeWorkingPatternAssignment",
    field: "EmployeeWorkingPatternAssignment.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "EmployeeWorkingPatternAssignment",
    field: "EmployeeWorkingPatternAssignment.employeeId",
    label: "employeeId",
    type: "string",
    filterable: true,
  },
  {
    model: "EmployeeWorkingPatternAssignment",
    field: "EmployeeWorkingPatternAssignment.workingPatternId",
    label: "workingPatternId",
    type: "string",
    filterable: true,
  },
  {
    model: "EmployeeWorkingPatternAssignment",
    field: "EmployeeWorkingPatternAssignment.effectiveDate",
    label: "effectiveDate",
    type: "date",
    filterable: true,
  },
  {
    model: "EmployeeWorkingPatternAssignment",
    field: "EmployeeWorkingPatternAssignment.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "EmployeeWorkingPatternAssignment",
    field: "EmployeeWorkingPatternAssignment.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "EventCategory",
    field: "EventCategory.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "EventCategory",
    field: "EventCategory.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "EventCategory",
    field: "EventCategory.requiresApproval",
    label: "requiresApproval",
    type: "boolean",
    filterable: true,
  },
  {
    model: "EventCategory",
    field: "EventCategory.adminOnly",
    label: "adminOnly",
    type: "boolean",
    filterable: true,
  },
  {
    model: "EventCategory",
    field: "EventCategory.isActive",
    label: "isActive",
    type: "boolean",
    filterable: true,
  },
  {
    model: "EventCategory",
    field: "EventCategory.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "EventCategory",
    field: "EventCategory.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "EventCategory",
    field: "EventCategory.categoryType",
    label: "categoryType",
    type: "string",
    filterable: true,
  },
  {
    model: "EventCategory",
    field: "EventCategory.color",
    label: "color",
    type: "string",
    filterable: true,
  },
  {
    model: "EventCategory",
    field: "EventCategory.systemDefined",
    label: "systemDefined",
    type: "boolean",
    filterable: true,
  },
  {
    model: "EventSubcategory",
    field: "EventSubcategory.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "EventSubcategory",
    field: "EventSubcategory.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "EventSubcategory",
    field: "EventSubcategory.eventCategoryId",
    label: "eventCategoryId",
    type: "string",
    filterable: true,
  },
  {
    model: "EventSubcategory",
    field: "EventSubcategory.isActive",
    label: "isActive",
    type: "boolean",
    filterable: true,
  },
  {
    model: "EventSubcategory",
    field: "EventSubcategory.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "EventSubcategory",
    field: "EventSubcategory.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.startDate",
    label: "startDate",
    type: "date",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.endDate",
    label: "endDate",
    type: "date",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.employeeId",
    label: "employeeId",
    type: "string",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.reason",
    label: "reason",
    type: "string",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.approvedById",
    label: "approvedById",
    type: "string",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.sickReasonId",
    label: "sickReasonId",
    type: "string",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.eventCategoryId",
    label: "eventCategoryId",
    type: "string",
    filterable: true,
  },
  {
    model: "LeaveRequest",
    field: "LeaveRequest.requesterId",
    label: "requesterId",
    type: "string",
    filterable: true,
  },
  {
    model: "LeaveEntitlement",
    field: "LeaveEntitlement.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "LeaveEntitlement",
    field: "LeaveEntitlement.employeeId",
    label: "employeeId",
    type: "string",
    filterable: true,
  },
  {
    model: "LeaveEntitlement",
    field: "LeaveEntitlement.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "LeaveEntitlement",
    field: "LeaveEntitlement.totalDays",
    label: "totalDays",
    type: "number",
    filterable: true,
  },
  {
    model: "LeaveEntitlement",
    field: "LeaveEntitlement.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "LeaveEntitlement",
    field: "LeaveEntitlement.usedDays",
    label: "usedDays",
    type: "number",
    filterable: true,
  },
  {
    model: "LeaveEntitlement",
    field: "LeaveEntitlement.daysAllocated",
    label: "daysAllocated",
    type: "number",
    filterable: true,
  },
  {
    model: "LeaveEntitlement",
    field: "LeaveEntitlement.eventCategoryId",
    label: "eventCategoryId",
    type: "string",
    filterable: true,
  },
  {
    model: "LeaveEntitlement",
    field: "LeaveEntitlement.carryoverDays",
    label: "carryoverDays",
    type: "number",
    filterable: true,
  },
  {
    model: "LeaveEntitlement",
    field: "LeaveEntitlement.carryoverExpiry",
    label: "carryoverExpiry",
    type: "date",
    filterable: true,
  },
  {
    model: "Department",
    field: "Department.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "Department",
    field: "Department.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "Department",
    field: "Department.companyId",
    label: "companyId",
    type: "string",
    filterable: true,
  },
  {
    model: "Company",
    field: "Company.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "Company",
    field: "Company.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "Company",
    field: "Company.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "Company",
    field: "Company.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "JobRole",
    field: "JobRole.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "JobRole",
    field: "JobRole.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "WorkingPattern",
    field: "WorkingPattern.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "WorkingPattern",
    field: "WorkingPattern.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "WorkingPattern",
    field: "WorkingPattern.active",
    label: "active",
    type: "boolean",
    filterable: true,
  },
  {
    model: "WorkingPattern",
    field: "WorkingPattern.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "WorkingPattern",
    field: "WorkingPattern.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "WorkingPattern",
    field: "WorkingPattern.description",
    label: "description",
    type: "string",
    filterable: true,
  },
  {
    model: "WorkingPatternDay",
    field: "WorkingPatternDay.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "WorkingPatternDay",
    field: "WorkingPatternDay.day",
    label: "day",
    type: "string",
    filterable: true,
  },
  {
    model: "WorkingPatternDay",
    field: "WorkingPatternDay.workingPatternWeekId",
    label: "workingPatternWeekId",
    type: "string",
    filterable: true,
  },
  {
    model: "WorkingPatternWeek",
    field: "WorkingPatternWeek.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "WorkingPatternWeek",
    field: "WorkingPatternWeek.weekNumber",
    label: "weekNumber",
    type: "number",
    filterable: true,
  },
  {
    model: "WorkingPatternWeek",
    field: "WorkingPatternWeek.workingPatternId",
    label: "workingPatternId",
    type: "string",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.companyId",
    label: "companyId",
    type: "string",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.eventCategoryId",
    label: "eventCategoryId",
    type: "string",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.enforceEntitlement",
    label: "enforceEntitlement",
    type: "boolean",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.noticePeriodDays",
    label: "noticePeriodDays",
    type: "number",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.maxConcurrent",
    label: "maxConcurrent",
    type: "number",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.maxBookingLength",
    label: "maxBookingLength",
    type: "number",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.maxCarryoverDays",
    label: "maxCarryoverDays",
    type: "number",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.carryoverExpiryMonths",
    label: "carryoverExpiryMonths",
    type: "number",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "EventRule",
    field: "EventRule.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "BlackoutDay",
    field: "BlackoutDay.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "BlackoutDay",
    field: "BlackoutDay.date",
    label: "date",
    type: "date",
    filterable: true,
  },
  {
    model: "BlackoutDay",
    field: "BlackoutDay.companyId",
    label: "companyId",
    type: "string",
    filterable: true,
  },
  {
    model: "BlackoutDay",
    field: "BlackoutDay.allEvents",
    label: "allEvents",
    type: "boolean",
    filterable: true,
  },
  {
    model: "BlackoutDay",
    field: "BlackoutDay.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "BlackoutDay",
    field: "BlackoutDay.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "FieldMetadata",
    field: "FieldMetadata.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "FieldMetadata",
    field: "FieldMetadata.model",
    label: "model",
    type: "string",
    filterable: true,
  },
  {
    model: "FieldMetadata",
    field: "FieldMetadata.field",
    label: "field",
    type: "string",
    filterable: true,
  },
  {
    model: "FieldMetadata",
    field: "FieldMetadata.label",
    label: "label",
    type: "string",
    filterable: true,
  },
  {
    model: "FieldMetadata",
    field: "FieldMetadata.fieldType",
    label: "fieldType",
    type: "string",
    filterable: true,
  },
  {
    model: "FieldMetadata",
    field: "FieldMetadata.isReportable",
    label: "isReportable",
    type: "boolean",
    filterable: true,
  },
  {
    model: "FieldMetadata",
    field: "FieldMetadata.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "SavedReport",
    field: "SavedReport.id",
    label: "id",
    type: "number",
    filterable: true,
  },
  {
    model: "SavedReport",
    field: "SavedReport.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "SavedReport",
    field: "SavedReport.category",
    label: "category",
    type: "string",
    filterable: true,
  },
  {
    model: "SavedReport",
    field: "SavedReport.fields",
    label: "fields",
    type: "string",
    filterable: true,
  },
  {
    model: "SavedReport",
    field: "SavedReport.createdBy",
    label: "createdBy",
    type: "string",
    filterable: true,
  },
  {
    model: "SavedReport",
    field: "SavedReport.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "SavedReport",
    field: "SavedReport.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "SavedReport",
    field: "SavedReport.companyId",
    label: "companyId",
    type: "string",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.category",
    label: "category",
    type: "string",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.path",
    label: "path",
    type: "string",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.size",
    label: "size",
    type: "number",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.type",
    label: "type",
    type: "string",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.uploaderId",
    label: "uploaderId",
    type: "string",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.companyId",
    label: "companyId",
    type: "string",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.deletedAt",
    label: "deletedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.url",
    label: "url",
    type: "string",
    filterable: true,
  },
  {
    model: "Document",
    field: "Document.employeeId",
    label: "employeeId",
    type: "string",
    filterable: true,
  },
  {
    model: "EmploymentCheck",
    field: "EmploymentCheck.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "EmploymentCheck",
    field: "EmploymentCheck.employeeId",
    label: "employeeId",
    type: "string",
    filterable: true,
  },
  {
    model: "EmploymentCheck",
    field: "EmploymentCheck.typeOfCheck",
    label: "typeOfCheck",
    type: "string",
    filterable: true,
  },
  {
    model: "EmploymentCheck",
    field: "EmploymentCheck.documentNumber",
    label: "documentNumber",
    type: "string",
    filterable: true,
  },
  {
    model: "EmploymentCheck",
    field: "EmploymentCheck.dateOfIssue",
    label: "dateOfIssue",
    type: "date",
    filterable: true,
  },
  {
    model: "EmploymentCheck",
    field: "EmploymentCheck.expiryDate",
    label: "expiryDate",
    type: "date",
    filterable: true,
  },
  {
    model: "EmploymentCheck",
    field: "EmploymentCheck.documentUrl",
    label: "documentUrl",
    type: "string",
    filterable: true,
  },
  {
    model: "EmploymentCheck",
    field: "EmploymentCheck.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "EmploymentCheck",
    field: "EmploymentCheck.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "DriverLicence",
    field: "DriverLicence.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "DriverLicence",
    field: "DriverLicence.employeeId",
    label: "employeeId",
    type: "string",
    filterable: true,
  },
  {
    model: "DriverLicence",
    field: "DriverLicence.type",
    label: "type",
    type: "string",
    filterable: true,
  },
  {
    model: "DriverLicence",
    field: "DriverLicence.licenceNumber",
    label: "licenceNumber",
    type: "string",
    filterable: true,
  },
  {
    model: "DriverLicence",
    field: "DriverLicence.issueDate",
    label: "issueDate",
    type: "date",
    filterable: true,
  },
  {
    model: "DriverLicence",
    field: "DriverLicence.expiryDate",
    label: "expiryDate",
    type: "date",
    filterable: true,
  },
  {
    model: "DriverLicence",
    field: "DriverLicence.documentId",
    label: "documentId",
    type: "string",
    filterable: true,
  },
  {
    model: "DriverLicence",
    field: "DriverLicence.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "DriverLicence",
    field: "DriverLicence.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "TrainingRecord",
    field: "TrainingRecord.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "TrainingRecord",
    field: "TrainingRecord.employeeId",
    label: "employeeId",
    type: "string",
    filterable: true,
  },
  {
    model: "TrainingRecord",
    field: "TrainingRecord.courseId",
    label: "courseId",
    type: "string",
    filterable: true,
  },
  {
    model: "TrainingRecord",
    field: "TrainingRecord.providerId",
    label: "providerId",
    type: "string",
    filterable: true,
  },
  {
    model: "TrainingRecord",
    field: "TrainingRecord.dateCompleted",
    label: "dateCompleted",
    type: "date",
    filterable: true,
  },
  {
    model: "TrainingRecord",
    field: "TrainingRecord.expiryDate",
    label: "expiryDate",
    type: "date",
    filterable: true,
  },
  {
    model: "TrainingRecord",
    field: "TrainingRecord.documentId",
    label: "documentId",
    type: "string",
    filterable: true,
  },
  {
    model: "TrainingRecord",
    field: "TrainingRecord.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "TrainingRecord",
    field: "TrainingRecord.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "ExpiryRule",
    field: "ExpiryRule.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "ExpiryRule",
    field: "ExpiryRule.category",
    label: "category",
    type: "string",
    filterable: true,
  },
  {
    model: "ExpiryRule",
    field: "ExpiryRule.daysBefore",
    label: "daysBefore",
    type: "number",
    filterable: true,
  },
  {
    model: "ExpiryRule",
    field: "ExpiryRule.notifyAdmin",
    label: "notifyAdmin",
    type: "boolean",
    filterable: true,
  },
  {
    model: "ExpiryRule",
    field: "ExpiryRule.notifyManager",
    label: "notifyManager",
    type: "boolean",
    filterable: true,
  },
  {
    model: "ExpiryRule",
    field: "ExpiryRule.notifyEmployee",
    label: "notifyEmployee",
    type: "boolean",
    filterable: true,
  },
  {
    model: "ExpiryRule",
    field: "ExpiryRule.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "ExpiryRule",
    field: "ExpiryRule.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "NewsPost",
    field: "NewsPost.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "NewsPost",
    field: "NewsPost.title",
    label: "title",
    type: "string",
    filterable: true,
  },
  {
    model: "NewsPost",
    field: "NewsPost.slug",
    label: "slug",
    type: "string",
    filterable: true,
  },
  {
    model: "NewsPost",
    field: "NewsPost.authorId",
    label: "authorId",
    type: "string",
    filterable: true,
  },
  {
    model: "NewsPost",
    field: "NewsPost.publishedAt",
    label: "publishedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "NewsPost",
    field: "NewsPost.pinned",
    label: "pinned",
    type: "boolean",
    filterable: true,
  },
  {
    model: "NewsPost",
    field: "NewsPost.videoEmbedUrl",
    label: "videoEmbedUrl",
    type: "string",
    filterable: true,
  },
  {
    model: "NewsPost",
    field: "NewsPost.sendEmail",
    label: "sendEmail",
    type: "boolean",
    filterable: true,
  },
  {
    model: "NewsPost",
    field: "NewsPost.createdAt",
    label: "createdAt",
    type: "date",
    filterable: true,
  },
  {
    model: "NewsPost",
    field: "NewsPost.updatedAt",
    label: "updatedAt",
    type: "date",
    filterable: true,
  },
  {
    model: "Course",
    field: "Course.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "Course",
    field: "Course.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "TrainingProvider",
    field: "TrainingProvider.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "TrainingProvider",
    field: "TrainingProvider.name",
    label: "name",
    type: "string",
    filterable: true,
  },
  {
    model: "Location",
    field: "Location.id",
    label: "id",
    type: "string",
    filterable: true,
  },
  {
    model: "Location",
    field: "Location.name",
    label: "name",
    type: "string",
    filterable: true,
  },
];
