export const defaultWorkflows = [
  {
    id: "90-day-trial",
    name: "90-Day Trial Period Reminder",
    description:
      "Automated reminders for New Zealand employment trial periods with manager notifications",
    category: "compliance",
    icon: "⚖️",
    tags: ["new-starter", "compliance", "nz-law"],
    nodes: [
      { id: "t1", type: "trigger", position: { x: 120, y: 80 }, data: { label: "Employee Start Date", config: { triggerType: "EMPLOYEE_START_DATE" } } },
      { id: "d1", type: "delay", position: { x: 120, y: 180 }, data: { label: "Delay 85 days", config: { days: 85 } } },
      { id: "a1", type: "action", position: { x: 120, y: 300 }, data: { label: "Notify Manager", actionType: "send_notification", config: { channels: ["email"], recipientType: "manager", subject: "90-day trial check-in", message: "Please review the employee during their 90-day trial period." } } },
      { id: "a2", type: "action", position: { x: 380, y: 300 }, data: { label: "Create HR Task", actionType: "create_task", config: { title: "Prepare trial review", description: "Schedule review meeting", assigneeType: "hr", dueDays: 5 } } },
    ],
    edges: [
      { id: "e_t1_d1", source: "t1", target: "d1" },
      { id: "e_d1_a1", source: "d1", target: "a1" },
      { id: "e_a1_a2", source: "a1", target: "a2" },
    ],
    config: {},
  },
  {
    id: "expiring-docs",
    name: "Expiring Documents Reminder",
    description: "Remind employees to update expiring documents 30 days prior",
    category: "compliance",
    icon: "📄",
    tags: ["documents", "compliance"],
    nodes: [
      { id: "t1", type: "trigger", position: { x: 120, y: 80 }, data: { label: "Document Expiring", config: { triggerType: "DOCUMENT_EXPIRING", daysBefore: 30 } } },
      { id: "c1", type: "condition", position: { x: 120, y: 200 }, data: { label: "Type = Right to Work", config: { field: "documentType", operator: "equals", value: "Right to Work" } } },
      { id: "a1", type: "action", position: { x: 120, y: 320 }, data: { label: "Email Employee", actionType: "send_notification", config: { channels: ["email"], recipientType: "employee", subject: "Your document is expiring", message: "Please upload an updated copy." } } },
      { id: "a2", type: "action", position: { x: 360, y: 320 }, data: { label: "Notify Manager", actionType: "send_notification", config: { channels: ["email"], recipientType: "manager", subject: "Employee document expiring", message: "Please remind your team member to update their document." } } },
    ],
    edges: [
      { id: "e_t1_c1", source: "t1", target: "c1" },
      { id: "e_c1_a1", source: "c1", target: "a1" },
      { id: "e_a1_a2", source: "a1", target: "a2" },
    ],
    config: {},
  },
  {
    id: "welcome-new-starter",
    name: "Welcome New Starter",
    description: "Send welcome email and create manager task",
    category: "hr",
    icon: "👋",
    tags: ["onboarding", "communication"],
    nodes: [
      { id: "t1", type: "trigger", position: { x: 120, y: 80 }, data: { label: "Employee Created", config: { triggerType: "EMPLOYEE_CREATED" } } },
      { id: "a1", type: "action", position: { x: 120, y: 220 }, data: { label: "Welcome Email", actionType: "send_notification", config: { channels: ["email"], recipientType: "employee", subject: "Welcome to the team!", message: "We’re excited to have you onboard." } } },
      { id: "a2", type: "action", position: { x: 380, y: 220 }, data: { label: "Manager Task", actionType: "create_task", config: { title: "Set up accounts", description: "Provision systems and schedule intros", assigneeType: "manager", dueDays: 7 } } },
    ],
    edges: [
      { id: "e_t1_a1", source: "t1", target: "a1" },
      { id: "e_a1_a2", source: "a1", target: "a2" },
    ],
    config: {},
  },
  {
    id: "form-followup",
    name: "Form Submission Follow-up",
    description: "Create task after key form submission",
    category: "operations",
    icon: "📝",
    tags: ["forms"],
    nodes: [
      { id: "t1", type: "trigger", position: { x: 120, y: 80 }, data: { label: "Form Submitted", config: { triggerType: "FORM_SUBMITTED", formId: "TEMPLATE" } } },
      { id: "a1", type: "action", position: { x: 120, y: 220 }, data: { label: "Create Review Task", actionType: "create_task", config: { title: "Review submission", description: "Check responses and follow up", assigneeType: "hr", dueDays: 3 } } },
    ],
    edges: [ { id: "e_t1_a1", source: "t1", target: "a1" } ],
    config: {},
  },
  {
    id: "leave-approval",
    name: "Leave Request Approval",
    description: "Notify approver when a leave request is created",
    category: "hr",
    icon: "🏝️",
    tags: ["leave"],
    nodes: [
      { id: "t1", type: "trigger", position: { x: 120, y: 80 }, data: { label: "Leave Request", config: { triggerType: "LEAVE_REQUEST" } } },
      { id: "a1", type: "action", position: { x: 120, y: 220 }, data: { label: "Notify Approver", actionType: "send_notification", config: { channels: ["email"], recipientType: "manager", subject: "Leave approval required", message: "Please review and approve the request." } } },
    ],
    edges: [ { id: "e_t1_a1", source: "t1", target: "a1" } ],
    config: {},
  },
  {
    id: "contract-expiry",
    name: "Fixed-term Contract Expiry",
    description: "Notify HR and manager 60 days before contract end",
    category: "compliance",
    icon: "📅",
    tags: ["contracts"],
    nodes: [
      { id: "t1", type: "trigger", position: { x: 120, y: 80 }, data: { label: "Contract Expiring", config: { triggerType: "CONTRACT_EXPIRING", daysBefore: 60 } } },
      { id: "a1", type: "action", position: { x: 120, y: 220 }, data: { label: "Notify HR", actionType: "send_notification", config: { channels: ["email"], recipientType: "hr", subject: "Contract expiring soon", message: "Review extension or offboarding plan." } } },
      { id: "a2", type: "action", position: { x: 360, y: 220 }, data: { label: "Notify Manager", actionType: "send_notification", config: { channels: ["email"], recipientType: "manager", subject: "Contract expiring", message: "Discuss next steps with HR and employee." } } },
    ],
    edges: [
      { id: "e_t1_a1", source: "t1", target: "a1" },
      { id: "e_a1_a2", source: "a1", target: "a2" },
    ],
    config: {},
  },
  {
    id: "performance-review",
    name: "Performance Review Completed",
    description: "Trigger follow-up actions after review",
    category: "engagement",
    icon: "⭐",
    tags: ["performance"],
    nodes: [
      { id: "t1", type: "trigger", position: { x: 120, y: 80 }, data: { label: "Review Completed", config: { triggerType: "PERFORMANCE_REVIEW_COMPLETED" } } },
      { id: "a1", type: "action", position: { x: 120, y: 220 }, data: { label: "Thank You Email", actionType: "send_notification", config: { channels: ["email"], recipientType: "employee", subject: "Thanks for completing your review", message: "Your manager will follow up with goals." } } },
    ],
    edges: [ { id: "e_t1_a1", source: "t1", target: "a1" } ],
    config: {},
  },
  {
    id: "probation-checkins",
    name: "Probation Check-ins",
    description: "Schedule 30/60/90 day manager check-ins",
    category: "hr",
    icon: "⏱️",
    tags: ["probation"],
    nodes: [
      { id: "t1", type: "trigger", position: { x: 120, y: 80 }, data: { label: "Employee Start Date", config: { triggerType: "EMPLOYEE_START_DATE" } } },
      { id: "d30", type: "delay", position: { x: 120, y: 180 }, data: { label: "Delay 30 days", config: { days: 30 } } },
      { id: "a30", type: "action", position: { x: 120, y: 280 }, data: { label: "30-day Check-in", actionType: "create_task", config: { title: "30-day check-in", assigneeType: "manager", dueDays: 3 } } },
      { id: "d60", type: "delay", position: { x: 360, y: 180 }, data: { label: "Delay 60 days", config: { days: 60 } } },
      { id: "a60", type: "action", position: { x: 360, y: 280 }, data: { label: "60-day Check-in", actionType: "create_task", config: { title: "60-day check-in", assigneeType: "manager", dueDays: 3 } } },
      { id: "d90", type: "delay", position: { x: 600, y: 180 }, data: { label: "Delay 90 days", config: { days: 90 } } },
      { id: "a90", type: "action", position: { x: 600, y: 280 }, data: { label: "90-day Check-in", actionType: "create_task", config: { title: "90-day check-in", assigneeType: "manager", dueDays: 3 } } },
    ],
    edges: [
      { id: "e_t1_d30", source: "t1", target: "d30" },
      { id: "e_d30_a30", source: "d30", target: "a30" },
      { id: "e_d30_d60", source: "d30", target: "d60" },
      { id: "e_d60_a60", source: "d60", target: "a60" },
      { id: "e_d60_d90", source: "d60", target: "d90" },
      { id: "e_d90_a90", source: "d90", target: "a90" },
    ],
    config: {},
  },
  {
    id: "offboarding-sequence",
    name: "Offboarding Sequence",
    description: "Coordinate offboarding tasks and access removal",
    category: "operations",
    icon: "🚪",
    tags: ["offboarding"],
    nodes: [
      { id: "t1", type: "trigger", position: { x: 120, y: 80 }, data: { label: "Employee Updated", config: { triggerType: "EMPLOYEE_UPDATED", field: "offboardingDate" } } },
      { id: "a1", type: "action", position: { x: 120, y: 220 }, data: { label: "Create Checklist", actionType: "create_task", config: { title: "Offboarding checklist", assigneeType: "hr", dueDays: 1 } } },
      { id: "a2", type: "action", position: { x: 360, y: 220 }, data: { label: "Notify IT", actionType: "send_notification", config: { channels: ["email"], recipientType: "specific", recipients: [], subject: "Access removal", message: "Remove accounts on last working day." } } },
    ],
    edges: [ { id: "e_t1_a1", source: "t1", target: "a1" }, { id: "e_a1_a2", source: "a1", target: "a2" } ],
    config: {},
  },
  {
    id: "anniversary-celebration",
    name: "Work Anniversary",
    description: "Send celebration message and badge",
    category: "engagement",
    icon: "🎉",
    tags: ["engagement"],
    nodes: [
      { id: "t1", type: "trigger", position: { x: 120, y: 80 }, data: { label: "Scheduled", config: { triggerType: "SCHEDULED", cron: "0 9 * * *" } } },
      { id: "a1", type: "action", position: { x: 120, y: 220 }, data: { label: "Celebrate", actionType: "send_notification", config: { channels: ["email"], recipientType: "employee", subject: "Happy work anniversary!", message: "Thanks for being with us." } } },
    ],
    edges: [ { id: "e_t1_a1", source: "t1", target: "a1" } ],
    config: {},
  },
];


